/* Enterprise Info */
export const GET_ENTERPRISE = 'GET_ENTERPRISE';
export const GET_ENTERPRISE_SUCCESS = 'GET_ENTERPRISE_SUCCESS';
export const GET_ENTERPRISE_FAILED = 'GET_ENTERPRISE_FAILED';
export const SELECT_ENTERPRISE = 'SELECT_ENTERPRISE';
export const SELECTALL_ENTERPRISE = 'SELECTALL_ENTERPRISE';
export const ACTIVE_ENTERPRISE = 'ACTIVE_ENTERPRISE';
export const ACTIVE_ENTERPRISE_SUCCESS = 'ACTIVE_ENTERPRISE_SUCCESS';
export const ACTIVE_ENTERPRISE_FAILED = 'ACTIVE_ENTERPRISE_FAILED';
export const PASSIVE_ENTERPRISE = 'PASSIVE_ENTERPRISE';
export const PASSIVE_ENTERPRISE_SUCCESS = 'PASSIVE_ENTERPRISE_SUCCESS';
export const PASSIVE_ENTERPRISE_FAILED = 'PASSIVE_ENTERPRISE_FAILED';
export const ADD_ENTERPRISE = 'ADD_ENTERPRISE';
export const ADD_ENTERPRISE_SUCCESS = 'ADD_ENTERPRISE_SUCCESS';
export const ADD_ENTERPRISE_FAILED = 'ADD_ENTERPRISE_FAILED';
export const UPDATE_ENTERPRISE = 'UPDATE_ENTERPRISE';
export const UPDATE_ENTERPRISE_SUCCESS = 'UPDATE_ENTERPRISE_SUCCESS';
export const UPDATE_ENTERPRISE_FAILED = 'UPDATE_ENTERPRISE_FAILED';
export const DELETE_ENTERPRISE = 'DELETE_ENTERPRISE';
export const DELETE_ENTERPRISE_SUCCESS = 'DELETE_ENTERPRISE_SUCCESS'
export const DELETE_ENTERPRISE_FAILED = 'DELETE_ENTERPRISE_FAILED'

/* Manager Info */
export const ADD_MANAGER = 'ADD_MANAGER';
export const ADD_MANAGER_SUCCESS = 'ADD_MANAGER_SUCCESS';
export const ADD_MANAGER_FAILED = 'ADD_MANAGER_FAILED';
export const GET_MANAGER = 'GET_MANAGER';
export const GET_MANAGER_SUCCESS = 'GET_MANAGER_SUCCESS';
export const GET_MANAGER_FAILED = 'GET_MANAGER_FAILED';
export const UPDATE_MANAGER = 'UPDATE_MANAGER';
export const UPDATE_MANAGER_SUCCESS = 'UPDATE_MANAGER_SUCCESS';
export const UPDATE_MANAGER_FAILED = 'UPDATE_MANAGER_FAILED';
export const DELETE_MANAGER = 'DELETE_MANAGER';
export const DELETE_MANAGER_SUCCESS = 'DELETE_MANAGER_SUCCESS'
export const DELETE_MANAGER_FAILED = 'DELETE_MANAGER_FAILED';
export const SELECT_MANAGER = 'SELECT_MANAGER';
export const SELECTALL_MANAGER = 'SELECTALL_MANAGER';
export const GET_ADEVERTISEMENT = 'GET_ADEVERTISEMENT';
export const GET_ADEVERTISEMENT_SUCCESS = 'GET_ADEVERTISEMENT_SUCCESS';

/* Audit */
export const GET_AUDIT = "GET_AUDIT";
export const GET_AUDIT_SUCCESS = "GET_AUDIT_SUCCESS";
export const GET_AUDIT_FAILED = "GET_AUDIT_FAILED";
export const SELECT_AUDIT = "SELECT_AUDIT";
export const SELECTALL_AUDIT = "SELECTALL_AUDIT";
export const ACTIVE_AUDIT = "ACTIVE_AUDIT";
export const ACTIVE_AUDIT_SUCCESS = "ACTIVE_AUDIT_SUCCESS";
export const ACTIVE_AUDIT_FAILED = "ACTIVE_AUDIT_FAILED";
export const PASSIVE_AUDIT = "PASSIVE_AUDIT";
export const PASSIVE_AUDIT_SUCCESS = "PASSIVE_AUDIT_SUCCESS";
export const PASSIVE_AUDIT_FAILED = "PASSIVE_AUDIT_FAILED";

